// Code generated by MockGen. DO NOT EDIT.
// Source: hub.go
//
// Generated by this command:
//
//	mockgen -source=hub.go -destination=./mock/hub_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	websocket "github.com/gorilla/websocket"
	gomock "go.uber.org/mock/gomock"
)

// MockHub is a mock of Hub interface.
type MockHub struct {
	ctrl     *gomock.Controller
	recorder *MockHubMockRecorder
	isgomock struct{}
}

// MockHubMockRecorder is the mock recorder for MockHub.
type MockHubMockRecorder struct {
	mock *MockHub
}

// NewMockHub creates a new mock instance.
func NewMockHub(ctrl *gomock.Controller) *MockHub {
	mock := &MockHub{ctrl: ctrl}
	mock.recorder = &MockHubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHub) EXPECT() *MockHubMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockHub) Register(userID uuid.UUID, conn *websocket.Conn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", userID, conn)
}

// Register indicates an expected call of Register.
func (mr *MockHubMockRecorder) Register(userID, conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockHub)(nil).Register), userID, conn)
}

// SendMessgeToOwner mocks base method.
func (m *MockHub) SendMessgeToOwner(userID uuid.UUID, data any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendMessgeToOwner", userID, data)
}

// SendMessgeToOwner indicates an expected call of SendMessgeToOwner.
func (mr *MockHubMockRecorder) SendMessgeToOwner(userID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessgeToOwner", reflect.TypeOf((*MockHub)(nil).SendMessgeToOwner), userID, data)
}

// Unregister mocks base method.
func (m *MockHub) Unregister(userID uuid.UUID, conn *websocket.Conn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unregister", userID, conn)
}

// Unregister indicates an expected call of Unregister.
func (mr *MockHubMockRecorder) Unregister(userID, conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockHub)(nil).Unregister), userID, conn)
}
