apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-service
  namespace: go-app
  labels:
    app: stream-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-service
  template:
    metadata:
      labels:
        app: stream-service
    spec:
      containers:
        - name: stream
          image: xomrkob/stream:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: stream-service-config
            - configMapRef:
                name: go-app-config
            - secretRef:
                name: go-app-secret
            - secretRef:
                name: minio-credentials
            - secretRef:
                name: casbin-redis

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: stream/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: stream/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
