apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream
  namespace: go-app
  labels:
    app: stream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream
  template:
    metadata:
      labels:
        app: stream
    spec:
      containers:
        - name: stream
          image: xomrkob/stream:0.1.1-fa02094cd4d1145daa2c5ecba49bb1a4ad189b56
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_ADDR
              value: ":8080"
            - name: DOMAIN
              value: go-app.example.com
            - name: DB_HOST
              value: postgresql
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "database1"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: go-app-secret
                  key: DB_PASS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: go-app-secret
                  key: DB_USER
            - name: JWT_ACCESS_PUBLIC_KEY_URL
              value: http://web-server-gin-service:80/api/auth/public-key
            - name: AUTH_SERVICE_ADDRESS
              value: web-server-gin-service:50051
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: stream/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: stream/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
