# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: go-app-config
  namespace: go-app
data:
  MINIO_ENDPOINT: "minio:9000"
  MINIO_BUCKET_NAME: "go-app-bucket"
  MINIO_USE_SSL: "false"
  MINIO_REGION: "us-east-1"
  REDIS_ADDR: "casbin-redis-master:6379"
  STREAM_SERVICE_ADDR: stream-service:50051
  JWT_ACCESS_PUBLIC_KEY_URL: "http://identity-service:80/auth/public-key"
  AUTH_SERVICE_ADDRESS: "identity-service:50051"
