apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stream-service
  namespace: go-app
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/http2-listener: "true"
    cert-manager.io/issuer: "ca-issuer"
    nginx.ingress.kubernetes.io/client-max-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
spec:
  tls:
    - hosts:
        - api.example.com
      secretName: stream-tls
  ingressClassName: nginx
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /stream
            pathType: Prefix
            backend:
              service:
                name: stream-service
                port:
                  number: 80
