apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stream-service
  namespace: go-app
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/http2-listener: "true"
    cert-manager.io/issuer: "ca-issuer"
    nginx.ingress.kubernetes.io/client-max-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://*.example.com"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,X-Amz-Content-Sha256,X-Amz-Date,X-Amz-Algorithm,X-Amz-Credential,X-Amz-SignedHeaders,X-Amz-Expires"
spec:
  tls:
    - hosts:
        - api.example.com
      secretName: stream-tls
  ingressClassName: nginx
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /stream
            pathType: Prefix
            backend:
              service:
                name: stream-service
                port:
                  number: 80
