# yaml-language-server: $schema=https://golangci-lint.run
version: 1
linters-settings:
  stylecheck:
    checks: ["all", "-ST1000"]
  revive:
    rules:
      - name: package-comments
        disabled: true
