// Code generated by MockGen. DO NOT EDIT.
// Source: stream_service.go
//
// Generated by this command:
//
//	mockgen -source=stream_service.go -destination=./mock/stream_service_mock.go -package=servicemock
//

// Package servicemock is a generated GoMock package.
package servicemock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	models "github.com/mrhumster/stream-service/internal/domain/models"
	repository "github.com/mrhumster/stream-service/internal/repository"
	service "github.com/mrhumster/stream-service/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockStreamService is a mock of StreamService interface.
type MockStreamService struct {
	ctrl     *gomock.Controller
	recorder *MockStreamServiceMockRecorder
	isgomock struct{}
}

// MockStreamServiceMockRecorder is the mock recorder for MockStreamService.
type MockStreamServiceMockRecorder struct {
	mock *MockStreamService
}

// NewMockStreamService creates a new mock instance.
func NewMockStreamService(ctrl *gomock.Controller) *MockStreamService {
	mock := &MockStreamService{ctrl: ctrl}
	mock.recorder = &MockStreamServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamService) EXPECT() *MockStreamServiceMockRecorder {
	return m.recorder
}

// CompleteStreamExport mocks base method.
func (m *MockStreamService) CompleteStreamExport(ctx context.Context, streamID uuid.UUID, size int64, exportErr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteStreamExport", ctx, streamID, size, exportErr)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteStreamExport indicates an expected call of CompleteStreamExport.
func (mr *MockStreamServiceMockRecorder) CompleteStreamExport(ctx, streamID, size, exportErr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteStreamExport", reflect.TypeOf((*MockStreamService)(nil).CompleteStreamExport), ctx, streamID, size, exportErr)
}

// CompleteStreamUpload mocks base method.
func (m *MockStreamService) CompleteStreamUpload(ctx context.Context, req service.CompleteStreamUploadRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteStreamUpload", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteStreamUpload indicates an expected call of CompleteStreamUpload.
func (mr *MockStreamServiceMockRecorder) CompleteStreamUpload(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteStreamUpload", reflect.TypeOf((*MockStreamService)(nil).CompleteStreamUpload), ctx, req)
}

// CreateStream mocks base method.
func (m *MockStreamService) CreateStream(ctx context.Context, req service.CreateStreamRequest) (*models.Stream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStream", ctx, req)
	ret0, _ := ret[0].(*models.Stream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStream indicates an expected call of CreateStream.
func (mr *MockStreamServiceMockRecorder) CreateStream(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStream", reflect.TypeOf((*MockStreamService)(nil).CreateStream), ctx, req)
}

// DeleteStream mocks base method.
func (m *MockStreamService) DeleteStream(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStream", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStream indicates an expected call of DeleteStream.
func (mr *MockStreamServiceMockRecorder) DeleteStream(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStream", reflect.TypeOf((*MockStreamService)(nil).DeleteStream), ctx, id)
}

// ForceStreamError mocks base method.
func (m *MockStreamService) ForceStreamError(ctx context.Context, streamID, userID uuid.UUID, isAdmin bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceStreamError", ctx, streamID, userID, isAdmin)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForceStreamError indicates an expected call of ForceStreamError.
func (mr *MockStreamServiceMockRecorder) ForceStreamError(ctx, streamID, userID, isAdmin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceStreamError", reflect.TypeOf((*MockStreamService)(nil).ForceStreamError), ctx, streamID, userID, isAdmin)
}

// ForceStreamErrorBatch mocks base method.
func (m *MockStreamService) ForceStreamErrorBatch(ctx context.Context, userID uuid.UUID, isAdmin bool, ids []uuid.UUID) (*service.StreamBatchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceStreamErrorBatch", ctx, userID, isAdmin, ids)
	ret0, _ := ret[0].(*service.StreamBatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForceStreamErrorBatch indicates an expected call of ForceStreamErrorBatch.
func (mr *MockStreamServiceMockRecorder) ForceStreamErrorBatch(ctx, userID, isAdmin, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceStreamErrorBatch", reflect.TypeOf((*MockStreamService)(nil).ForceStreamErrorBatch), ctx, userID, isAdmin, ids)
}

// GetFileByKey mocks base method.
func (m *MockStreamService) GetFileByKey(ctx context.Context, req *service.GetFileByKeyRequest) (*service.GetFileByKeyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileByKey", ctx, req)
	ret0, _ := ret[0].(*service.GetFileByKeyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileByKey indicates an expected call of GetFileByKey.
func (mr *MockStreamServiceMockRecorder) GetFileByKey(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileByKey", reflect.TypeOf((*MockStreamService)(nil).GetFileByKey), ctx, req)
}

// GetStream mocks base method.
func (m *MockStreamService) GetStream(ctx context.Context, id uuid.UUID) (*models.Stream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStream", ctx, id)
	ret0, _ := ret[0].(*models.Stream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStream indicates an expected call of GetStream.
func (mr *MockStreamServiceMockRecorder) GetStream(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStream", reflect.TypeOf((*MockStreamService)(nil).GetStream), ctx, id)
}

// GetStreamExport mocks base method.
func (m *MockStreamService) GetStreamExport(ctx context.Context, streamID, userUUID uuid.UUID) (*service.StreamExportInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreamExport", ctx, streamID, userUUID)
	ret0, _ := ret[0].(*service.StreamExportInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamExport indicates an expected call of GetStreamExport.
func (mr *MockStreamServiceMockRecorder) GetStreamExport(ctx, streamID, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamExport", reflect.TypeOf((*MockStreamService)(nil).GetStreamExport), ctx, streamID, userUUID)
}

// GetStreamStatus mocks base method.
func (m *MockStreamService) GetStreamStatus(ctx context.Context, id uuid.UUID) (*models.Stream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreamStatus", ctx, id)
	ret0, _ := ret[0].(*models.Stream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamStatus indicates an expected call of GetStreamStatus.
func (mr *MockStreamServiceMockRecorder) GetStreamStatus(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamStatus", reflect.TypeOf((*MockStreamService)(nil).GetStreamStatus), ctx, id)
}

// ListStreams mocks base method.
func (m *MockStreamService) ListStreams(ctx context.Context, filter repository.StreamFilter) ([]*models.Stream, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStreams", ctx, filter)
	ret0, _ := ret[0].([]*models.Stream)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListStreams indicates an expected call of ListStreams.
func (mr *MockStreamServiceMockRecorder) ListStreams(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStreams", reflect.TypeOf((*MockStreamService)(nil).ListStreams), ctx, filter)
}

// ListUserStreams mocks base method.
func (m *MockStreamService) ListUserStreams(ctx context.Context, userID uuid.UUID, filter repository.StreamFilter) ([]*models.Stream, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserStreams", ctx, userID, filter)
	ret0, _ := ret[0].([]*models.Stream)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUserStreams indicates an expected call of ListUserStreams.
func (mr *MockStreamServiceMockRecorder) ListUserStreams(ctx, userID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserStreams", reflect.TypeOf((*MockStreamService)(nil).ListUserStreams), ctx, userID, filter)
}

// OpenStreamDownload mocks base method.
func (m *MockStreamService) OpenStreamDownload(ctx context.Context, streamID, userUUID uuid.UUID) (*service.DownloadStreamInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenStreamDownload", ctx, streamID, userUUID)
	ret0, _ := ret[0].(*service.DownloadStreamInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenStreamDownload indicates an expected call of OpenStreamDownload.
func (mr *MockStreamServiceMockRecorder) OpenStreamDownload(ctx, streamID, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenStreamDownload", reflect.TypeOf((*MockStreamService)(nil).OpenStreamDownload), ctx, streamID, userUUID)
}

// ProcessFacesBatch mocks base method.
func (m *MockStreamService) ProcessFacesBatch(ctx context.Context, userID uuid.UUID, isAdmin bool, ids []uuid.UUID) (*service.FacesBatchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessFacesBatch", ctx, userID, isAdmin, ids)
	ret0, _ := ret[0].(*service.FacesBatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessFacesBatch indicates an expected call of ProcessFacesBatch.
func (mr *MockStreamServiceMockRecorder) ProcessFacesBatch(ctx, userID, isAdmin, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessFacesBatch", reflect.TypeOf((*MockStreamService)(nil).ProcessFacesBatch), ctx, userID, isAdmin, ids)
}

// ProcessFacesStream mocks base method.
func (m *MockStreamService) ProcessFacesStream(ctx context.Context, streamID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessFacesStream", ctx, streamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessFacesStream indicates an expected call of ProcessFacesStream.
func (mr *MockStreamServiceMockRecorder) ProcessFacesStream(ctx, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessFacesStream", reflect.TypeOf((*MockStreamService)(nil).ProcessFacesStream), ctx, streamID)
}

// PublishStream mocks base method.
func (m *MockStreamService) PublishStream(ctx context.Context, streamID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishStream", ctx, streamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishStream indicates an expected call of PublishStream.
func (mr *MockStreamServiceMockRecorder) PublishStream(ctx, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishStream", reflect.TypeOf((*MockStreamService)(nil).PublishStream), ctx, streamID)
}

// ReprocessStream mocks base method.
func (m *MockStreamService) ReprocessStream(ctx context.Context, streamID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReprocessStream", ctx, streamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReprocessStream indicates an expected call of ReprocessStream.
func (mr *MockStreamServiceMockRecorder) ReprocessStream(ctx, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReprocessStream", reflect.TypeOf((*MockStreamService)(nil).ReprocessStream), ctx, streamID)
}

// ReprocessStreamBatch mocks base method.
func (m *MockStreamService) ReprocessStreamBatch(ctx context.Context, userID uuid.UUID, isAdmin bool, ids []uuid.UUID) (*service.StreamBatchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReprocessStreamBatch", ctx, userID, isAdmin, ids)
	ret0, _ := ret[0].(*service.StreamBatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReprocessStreamBatch indicates an expected call of ReprocessStreamBatch.
func (mr *MockStreamServiceMockRecorder) ReprocessStreamBatch(ctx, userID, isAdmin, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReprocessStreamBatch", reflect.TypeOf((*MockStreamService)(nil).ReprocessStreamBatch), ctx, userID, isAdmin, ids)
}

// RequestStreamExport mocks base method.
func (m *MockStreamService) RequestStreamExport(ctx context.Context, streamID, userUUID uuid.UUID, email string) (*service.StreamExportInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestStreamExport", ctx, streamID, userUUID, email)
	ret0, _ := ret[0].(*service.StreamExportInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestStreamExport indicates an expected call of RequestStreamExport.
func (mr *MockStreamServiceMockRecorder) RequestStreamExport(ctx, streamID, userUUID, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestStreamExport", reflect.TypeOf((*MockStreamService)(nil).RequestStreamExport), ctx, streamID, userUUID, email)
}

// StartStreamUpload mocks base method.
func (m *MockStreamService) StartStreamUpload(ctx context.Context, req service.StartUploadRequest) (*service.UploadInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartStreamUpload", ctx, req)
	ret0, _ := ret[0].(*service.UploadInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartStreamUpload indicates an expected call of StartStreamUpload.
func (mr *MockStreamServiceMockRecorder) StartStreamUpload(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartStreamUpload", reflect.TypeOf((*MockStreamService)(nil).StartStreamUpload), ctx, req)
}

// UnpublishStream mocks base method.
func (m *MockStreamService) UnpublishStream(ctx context.Context, streamID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpublishStream", ctx, streamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnpublishStream indicates an expected call of UnpublishStream.
func (mr *MockStreamServiceMockRecorder) UnpublishStream(ctx, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpublishStream", reflect.TypeOf((*MockStreamService)(nil).UnpublishStream), ctx, streamID)
}

// UpdateStream mocks base method.
func (m *MockStreamService) UpdateStream(ctx context.Context, id uuid.UUID, req service.UpdateStreamRequest) (*models.Stream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStream", ctx, id, req)
	ret0, _ := ret[0].(*models.Stream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStream indicates an expected call of UpdateStream.
func (mr *MockStreamServiceMockRecorder) UpdateStream(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStream", reflect.TypeOf((*MockStreamService)(nil).UpdateStream), ctx, id, req)
}

// UpdateStreamMetadata mocks base method.
func (m *MockStreamService) UpdateStreamMetadata(ctx context.Context, req *service.UpdateStreamMetadataRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStreamMetadata", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStreamMetadata indicates an expected call of UpdateStreamMetadata.
func (mr *MockStreamServiceMockRecorder) UpdateStreamMetadata(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStreamMetadata", reflect.TypeOf((*MockStreamService)(nil).UpdateStreamMetadata), ctx, req)
}

// UpdateStreamProcessing mocks base method.
func (m *MockStreamService) UpdateStreamProcessing(ctx context.Context, req *service.UpdateStreamProcessingRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStreamProcessing", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStreamProcessing indicates an expected call of UpdateStreamProcessing.
func (mr *MockStreamServiceMockRecorder) UpdateStreamProcessing(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStreamProcessing", reflect.TypeOf((*MockStreamService)(nil).UpdateStreamProcessing), ctx, req)
}

// UpdateStreamStatus mocks base method.
func (m *MockStreamService) UpdateStreamStatus(ctx context.Context, streamID uuid.UUID, status models.StreamStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStreamStatus", ctx, streamID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStreamStatus indicates an expected call of UpdateStreamStatus.
func (mr *MockStreamServiceMockRecorder) UpdateStreamStatus(ctx, streamID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStreamStatus", reflect.TypeOf((*MockStreamService)(nil).UpdateStreamStatus), ctx, streamID, status)
}

// UploadPart mocks base method.
func (m *MockStreamService) UploadPart(ctx context.Context, req service.UploadPartRequest) (*models.MultipartPart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadPart", ctx, req)
	ret0, _ := ret[0].(*models.MultipartPart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadPart indicates an expected call of UploadPart.
func (mr *MockStreamServiceMockRecorder) UploadPart(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPart", reflect.TypeOf((*MockStreamService)(nil).UploadPart), ctx, req)
}

// UploadVideo mocks base method.
func (m *MockStreamService) UploadVideo(ctx context.Context, req service.UploadVideoRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadVideo", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadVideo indicates an expected call of UploadVideo.
func (mr *MockStreamServiceMockRecorder) UploadVideo(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadVideo", reflect.TypeOf((*MockStreamService)(nil).UploadVideo), ctx, req)
}
