// Code generated by MockGen. DO NOT EDIT.
// Source: stream_service.go
//
// Generated by this command:
//
//	mockgen -source=stream_service.go -destination=./mock/stream_service_mock.go -package=servicemock
//

// Package servicemock is a generated GoMock package.
package servicemock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	models "github.com/mrhumster/stream-service/internal/domain/models"
	repository "github.com/mrhumster/stream-service/internal/repository"
	service "github.com/mrhumster/stream-service/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockStreamService is a mock of StreamService interface.
type MockStreamService struct {
	ctrl     *gomock.Controller
	recorder *MockStreamServiceMockRecorder
	isgomock struct{}
}

// MockStreamServiceMockRecorder is the mock recorder for MockStreamService.
type MockStreamServiceMockRecorder struct {
	mock *MockStreamService
}

// NewMockStreamService creates a new mock instance.
func NewMockStreamService(ctrl *gomock.Controller) *MockStreamService {
	mock := &MockStreamService{ctrl: ctrl}
	mock.recorder = &MockStreamServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamService) EXPECT() *MockStreamServiceMockRecorder {
	return m.recorder
}

// CanUserAccessStream mocks base method.
func (m *MockStreamService) CanUserAccessStream(ctx context.Context, userID, streamID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanUserAccessStream", ctx, userID, streamID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanUserAccessStream indicates an expected call of CanUserAccessStream.
func (mr *MockStreamServiceMockRecorder) CanUserAccessStream(ctx, userID, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanUserAccessStream", reflect.TypeOf((*MockStreamService)(nil).CanUserAccessStream), ctx, userID, streamID)
}

// CompleteStreamUpload mocks base method.
func (m *MockStreamService) CompleteStreamUpload(ctx context.Context, streamID, userID uuid.UUID, parts []models.MultipartPart) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteStreamUpload", ctx, streamID, userID, parts)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteStreamUpload indicates an expected call of CompleteStreamUpload.
func (mr *MockStreamServiceMockRecorder) CompleteStreamUpload(ctx, streamID, userID, parts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteStreamUpload", reflect.TypeOf((*MockStreamService)(nil).CompleteStreamUpload), ctx, streamID, userID, parts)
}

// CreateStream mocks base method.
func (m *MockStreamService) CreateStream(ctx context.Context, req service.CreateStreamRequest) (*models.Stream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStream", ctx, req)
	ret0, _ := ret[0].(*models.Stream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStream indicates an expected call of CreateStream.
func (mr *MockStreamServiceMockRecorder) CreateStream(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStream", reflect.TypeOf((*MockStreamService)(nil).CreateStream), ctx, req)
}

// DeleteStream mocks base method.
func (m *MockStreamService) DeleteStream(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStream", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStream indicates an expected call of DeleteStream.
func (mr *MockStreamServiceMockRecorder) DeleteStream(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStream", reflect.TypeOf((*MockStreamService)(nil).DeleteStream), ctx, id)
}

// GenerateDownloadURL mocks base method.
func (m *MockStreamService) GenerateDownloadURL(ctx context.Context, streamID uuid.UUID) (*service.GenerateDownloadURLInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDownloadURL", ctx, streamID)
	ret0, _ := ret[0].(*service.GenerateDownloadURLInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateDownloadURL indicates an expected call of GenerateDownloadURL.
func (mr *MockStreamServiceMockRecorder) GenerateDownloadURL(ctx, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDownloadURL", reflect.TypeOf((*MockStreamService)(nil).GenerateDownloadURL), ctx, streamID)
}

// GetStream mocks base method.
func (m *MockStreamService) GetStream(ctx context.Context, id uuid.UUID) (*models.Stream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStream", ctx, id)
	ret0, _ := ret[0].(*models.Stream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStream indicates an expected call of GetStream.
func (mr *MockStreamServiceMockRecorder) GetStream(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStream", reflect.TypeOf((*MockStreamService)(nil).GetStream), ctx, id)
}

// ListStreams mocks base method.
func (m *MockStreamService) ListStreams(ctx context.Context, filter repository.StreamFilter) ([]*models.Stream, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStreams", ctx, filter)
	ret0, _ := ret[0].([]*models.Stream)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListStreams indicates an expected call of ListStreams.
func (mr *MockStreamServiceMockRecorder) ListStreams(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStreams", reflect.TypeOf((*MockStreamService)(nil).ListStreams), ctx, filter)
}

// ListUserStreams mocks base method.
func (m *MockStreamService) ListUserStreams(ctx context.Context, userID uuid.UUID) ([]*models.Stream, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserStreams", ctx, userID)
	ret0, _ := ret[0].([]*models.Stream)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUserStreams indicates an expected call of ListUserStreams.
func (mr *MockStreamServiceMockRecorder) ListUserStreams(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserStreams", reflect.TypeOf((*MockStreamService)(nil).ListUserStreams), ctx, userID)
}

// PublishStream mocks base method.
func (m *MockStreamService) PublishStream(ctx context.Context, streamID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishStream", ctx, streamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishStream indicates an expected call of PublishStream.
func (mr *MockStreamServiceMockRecorder) PublishStream(ctx, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishStream", reflect.TypeOf((*MockStreamService)(nil).PublishStream), ctx, streamID)
}

// StartStreamUpload mocks base method.
func (m *MockStreamService) StartStreamUpload(ctx context.Context, req service.StartUploadRequest) (*service.UploadInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartStreamUpload", ctx, req)
	ret0, _ := ret[0].(*service.UploadInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartStreamUpload indicates an expected call of StartStreamUpload.
func (mr *MockStreamServiceMockRecorder) StartStreamUpload(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartStreamUpload", reflect.TypeOf((*MockStreamService)(nil).StartStreamUpload), ctx, req)
}

// UnpublishStream mocks base method.
func (m *MockStreamService) UnpublishStream(ctx context.Context, streamID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpublishStream", ctx, streamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnpublishStream indicates an expected call of UnpublishStream.
func (mr *MockStreamServiceMockRecorder) UnpublishStream(ctx, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpublishStream", reflect.TypeOf((*MockStreamService)(nil).UnpublishStream), ctx, streamID)
}

// UpdateStream mocks base method.
func (m *MockStreamService) UpdateStream(ctx context.Context, id uuid.UUID, req service.UpdateStreamRequest) (*models.Stream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStream", ctx, id, req)
	ret0, _ := ret[0].(*models.Stream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStream indicates an expected call of UpdateStream.
func (mr *MockStreamServiceMockRecorder) UpdateStream(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStream", reflect.TypeOf((*MockStreamService)(nil).UpdateStream), ctx, id, req)
}

// UpdateStreamStatus mocks base method.
func (m *MockStreamService) UpdateStreamStatus(ctx context.Context, streamID uuid.UUID, status models.StreamStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStreamStatus", ctx, streamID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStreamStatus indicates an expected call of UpdateStreamStatus.
func (mr *MockStreamServiceMockRecorder) UpdateStreamStatus(ctx, streamID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStreamStatus", reflect.TypeOf((*MockStreamService)(nil).UpdateStreamStatus), ctx, streamID, status)
}

// UploadPart mocks base method.
func (m *MockStreamService) UploadPart(ctx context.Context, req service.UploadPartRequest) (*models.MultipartPart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadPart", ctx, req)
	ret0, _ := ret[0].(*models.MultipartPart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadPart indicates an expected call of UploadPart.
func (mr *MockStreamServiceMockRecorder) UploadPart(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPart", reflect.TypeOf((*MockStreamService)(nil).UploadPart), ctx, req)
}

// UploadVideo mocks base method.
func (m *MockStreamService) UploadVideo(ctx context.Context, req service.UploadVideoRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadVideo", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadVideo indicates an expected call of UploadVideo.
func (mr *MockStreamServiceMockRecorder) UploadVideo(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadVideo", reflect.TypeOf((*MockStreamService)(nil).UploadVideo), ctx, req)
}
