// Code generated by MockGen. DO NOT EDIT.
// Source: filestorage.go
//
// Generated by this command:
//
//	mockgen -source=filestorage.go -destination=mock/filestorage_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	url "net/url"
	reflect "reflect"
	time "time"

	storage "github.com/mrhumster/stream-service/internal/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockFileStorage is a mock of FileStorage interface.
type MockFileStorage struct {
	ctrl     *gomock.Controller
	recorder *MockFileStorageMockRecorder
	isgomock struct{}
}

// MockFileStorageMockRecorder is the mock recorder for MockFileStorage.
type MockFileStorageMockRecorder struct {
	mock *MockFileStorage
}

// NewMockFileStorage creates a new mock instance.
func NewMockFileStorage(ctrl *gomock.Controller) *MockFileStorage {
	mock := &MockFileStorage{ctrl: ctrl}
	mock.recorder = &MockFileStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStorage) EXPECT() *MockFileStorageMockRecorder {
	return m.recorder
}

// AbortMultipart mocks base method.
func (m *MockFileStorage) AbortMultipart(ctx context.Context, path, uploadID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbortMultipart", ctx, path, uploadID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AbortMultipart indicates an expected call of AbortMultipart.
func (mr *MockFileStorageMockRecorder) AbortMultipart(ctx, path, uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortMultipart", reflect.TypeOf((*MockFileStorage)(nil).AbortMultipart), ctx, path, uploadID)
}

// CompleteMultipart mocks base method.
func (m *MockFileStorage) CompleteMultipart(ctx context.Context, path, uploadID string, parts []storage.MultipartPart) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteMultipart", ctx, path, uploadID, parts)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteMultipart indicates an expected call of CompleteMultipart.
func (mr *MockFileStorageMockRecorder) CompleteMultipart(ctx, path, uploadID, parts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteMultipart", reflect.TypeOf((*MockFileStorage)(nil).CompleteMultipart), ctx, path, uploadID, parts)
}

// Delete mocks base method.
func (m *MockFileStorage) Delete(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFileStorageMockRecorder) Delete(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFileStorage)(nil).Delete), ctx, path)
}

// Download mocks base method.
func (m *MockFileStorage) Download(ctx context.Context, path string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, path)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockFileStorageMockRecorder) Download(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockFileStorage)(nil).Download), ctx, path)
}

// Exists mocks base method.
func (m *MockFileStorage) Exists(ctx context.Context, path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockFileStorageMockRecorder) Exists(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockFileStorage)(nil).Exists), ctx, path)
}

// GeneratePresignedURL mocks base method.
func (m *MockFileStorage) GeneratePresignedURL(ctx context.Context, path, filename string, expires time.Duration) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePresignedURL", ctx, path, filename, expires)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePresignedURL indicates an expected call of GeneratePresignedURL.
func (mr *MockFileStorageMockRecorder) GeneratePresignedURL(ctx, path, filename, expires any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePresignedURL", reflect.TypeOf((*MockFileStorage)(nil).GeneratePresignedURL), ctx, path, filename, expires)
}

// GetBucketName mocks base method.
func (m *MockFileStorage) GetBucketName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBucketName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBucketName indicates an expected call of GetBucketName.
func (mr *MockFileStorageMockRecorder) GetBucketName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBucketName", reflect.TypeOf((*MockFileStorage)(nil).GetBucketName))
}

// InitMultipart mocks base method.
func (m *MockFileStorage) InitMultipart(ctx context.Context, path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitMultipart", ctx, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitMultipart indicates an expected call of InitMultipart.
func (mr *MockFileStorageMockRecorder) InitMultipart(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitMultipart", reflect.TypeOf((*MockFileStorage)(nil).InitMultipart), ctx, path)
}

// Upload mocks base method.
func (m *MockFileStorage) Upload(ctx context.Context, path string, data io.Reader, size int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, path, data, size)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockFileStorageMockRecorder) Upload(ctx, path, data, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockFileStorage)(nil).Upload), ctx, path, data, size)
}

// UploadPart mocks base method.
func (m *MockFileStorage) UploadPart(ctx context.Context, path, uploadID string, partNumber int, data io.Reader, size int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadPart", ctx, path, uploadID, partNumber, data, size)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadPart indicates an expected call of UploadPart.
func (mr *MockFileStorageMockRecorder) UploadPart(ctx, path, uploadID, partNumber, data, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPart", reflect.TypeOf((*MockFileStorage)(nil).UploadPart), ctx, path, uploadID, partNumber, data, size)
}
