// Code generated by MockGen. DO NOT EDIT.
// Source: minio_client.go
//
// Generated by this command:
//
//	mockgen -source=minio_client.go -destination=mock/minio_client_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	url "net/url"
	reflect "reflect"
	time "time"

	minio "github.com/minio/minio-go/v7"
	gomock "go.uber.org/mock/gomock"
)

// MockMinIOClient is a mock of MinIOClient interface.
type MockMinIOClient struct {
	ctrl     *gomock.Controller
	recorder *MockMinIOClientMockRecorder
	isgomock struct{}
}

// MockMinIOClientMockRecorder is the mock recorder for MockMinIOClient.
type MockMinIOClientMockRecorder struct {
	mock *MockMinIOClient
}

// NewMockMinIOClient creates a new mock instance.
func NewMockMinIOClient(ctrl *gomock.Controller) *MockMinIOClient {
	mock := &MockMinIOClient{ctrl: ctrl}
	mock.recorder = &MockMinIOClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMinIOClient) EXPECT() *MockMinIOClientMockRecorder {
	return m.recorder
}

// AbortMultipartUpload mocks base method.
func (m *MockMinIOClient) AbortMultipartUpload(ctx context.Context, bucket, object, uploadID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbortMultipartUpload", ctx, bucket, object, uploadID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AbortMultipartUpload indicates an expected call of AbortMultipartUpload.
func (mr *MockMinIOClientMockRecorder) AbortMultipartUpload(ctx, bucket, object, uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortMultipartUpload", reflect.TypeOf((*MockMinIOClient)(nil).AbortMultipartUpload), ctx, bucket, object, uploadID)
}

// BucketExists mocks base method.
func (m *MockMinIOClient) BucketExists(ctx context.Context, bucketName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BucketExists", ctx, bucketName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BucketExists indicates an expected call of BucketExists.
func (mr *MockMinIOClientMockRecorder) BucketExists(ctx, bucketName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BucketExists", reflect.TypeOf((*MockMinIOClient)(nil).BucketExists), ctx, bucketName)
}

// CompleteMultipartUpload mocks base method.
func (m *MockMinIOClient) CompleteMultipartUpload(ctx context.Context, bucket, object, uploadID string, parts []minio.CompletePart, opts minio.PutObjectOptions) (minio.UploadInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteMultipartUpload", ctx, bucket, object, uploadID, parts, opts)
	ret0, _ := ret[0].(minio.UploadInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteMultipartUpload indicates an expected call of CompleteMultipartUpload.
func (mr *MockMinIOClientMockRecorder) CompleteMultipartUpload(ctx, bucket, object, uploadID, parts, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteMultipartUpload", reflect.TypeOf((*MockMinIOClient)(nil).CompleteMultipartUpload), ctx, bucket, object, uploadID, parts, opts)
}

// GetObject mocks base method.
func (m *MockMinIOClient) GetObject(ctx context.Context, bucketName, objectName string, opts minio.GetObjectOptions) (*minio.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, bucketName, objectName, opts)
	ret0, _ := ret[0].(*minio.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockMinIOClientMockRecorder) GetObject(ctx, bucketName, objectName, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockMinIOClient)(nil).GetObject), ctx, bucketName, objectName, opts)
}

// ListObjects mocks base method.
func (m *MockMinIOClient) ListObjects(ctx context.Context, dirPath string, opt minio.ListObjectsOptions) <-chan minio.ObjectInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", ctx, dirPath, opt)
	ret0, _ := ret[0].(<-chan minio.ObjectInfo)
	return ret0
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockMinIOClientMockRecorder) ListObjects(ctx, dirPath, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockMinIOClient)(nil).ListObjects), ctx, dirPath, opt)
}

// MakeBucket mocks base method.
func (m *MockMinIOClient) MakeBucket(ctx context.Context, bucketName string, opts minio.MakeBucketOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeBucket", ctx, bucketName, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// MakeBucket indicates an expected call of MakeBucket.
func (mr *MockMinIOClientMockRecorder) MakeBucket(ctx, bucketName, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeBucket", reflect.TypeOf((*MockMinIOClient)(nil).MakeBucket), ctx, bucketName, opts)
}

// NewMultipartUpload mocks base method.
func (m *MockMinIOClient) NewMultipartUpload(ctx context.Context, bucket, object string, opts minio.PutObjectOptions) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewMultipartUpload", ctx, bucket, object, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewMultipartUpload indicates an expected call of NewMultipartUpload.
func (mr *MockMinIOClientMockRecorder) NewMultipartUpload(ctx, bucket, object, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMultipartUpload", reflect.TypeOf((*MockMinIOClient)(nil).NewMultipartUpload), ctx, bucket, object, opts)
}

// PresignedGetObject mocks base method.
func (m *MockMinIOClient) PresignedGetObject(ctx context.Context, bucketName, objectName string, expires time.Duration, reqParams url.Values) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignedGetObject", ctx, bucketName, objectName, expires, reqParams)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignedGetObject indicates an expected call of PresignedGetObject.
func (mr *MockMinIOClientMockRecorder) PresignedGetObject(ctx, bucketName, objectName, expires, reqParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignedGetObject", reflect.TypeOf((*MockMinIOClient)(nil).PresignedGetObject), ctx, bucketName, objectName, expires, reqParams)
}

// PutObject mocks base method.
func (m *MockMinIOClient) PutObject(ctx context.Context, bucketName, objectName string, reader io.Reader, objectSize int64, opts minio.PutObjectOptions) (minio.UploadInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, bucketName, objectName, reader, objectSize, opts)
	ret0, _ := ret[0].(minio.UploadInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObject indicates an expected call of PutObject.
func (mr *MockMinIOClientMockRecorder) PutObject(ctx, bucketName, objectName, reader, objectSize, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockMinIOClient)(nil).PutObject), ctx, bucketName, objectName, reader, objectSize, opts)
}

// PutObjectPart mocks base method.
func (m *MockMinIOClient) PutObjectPart(ctx context.Context, bucket, object, uploadID string, partID int, data io.Reader, size int64, opts minio.PutObjectPartOptions) (minio.ObjectPart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObjectPart", ctx, bucket, object, uploadID, partID, data, size, opts)
	ret0, _ := ret[0].(minio.ObjectPart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObjectPart indicates an expected call of PutObjectPart.
func (mr *MockMinIOClientMockRecorder) PutObjectPart(ctx, bucket, object, uploadID, partID, data, size, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObjectPart", reflect.TypeOf((*MockMinIOClient)(nil).PutObjectPart), ctx, bucket, object, uploadID, partID, data, size, opts)
}

// RemoveObject mocks base method.
func (m *MockMinIOClient) RemoveObject(ctx context.Context, bucketName, objectName string, opts minio.RemoveObjectOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveObject", ctx, bucketName, objectName, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveObject indicates an expected call of RemoveObject.
func (mr *MockMinIOClientMockRecorder) RemoveObject(ctx, bucketName, objectName, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveObject", reflect.TypeOf((*MockMinIOClient)(nil).RemoveObject), ctx, bucketName, objectName, opts)
}

// RemoveObjects mocks base method.
func (m *MockMinIOClient) RemoveObjects(ctx context.Context, bucketName string, objectsCh <-chan minio.ObjectInfo, opts minio.RemoveObjectsOptions) <-chan minio.RemoveObjectError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveObjects", ctx, bucketName, objectsCh, opts)
	ret0, _ := ret[0].(<-chan minio.RemoveObjectError)
	return ret0
}

// RemoveObjects indicates an expected call of RemoveObjects.
func (mr *MockMinIOClientMockRecorder) RemoveObjects(ctx, bucketName, objectsCh, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveObjects", reflect.TypeOf((*MockMinIOClient)(nil).RemoveObjects), ctx, bucketName, objectsCh, opts)
}

// StatObject mocks base method.
func (m *MockMinIOClient) StatObject(ctx context.Context, bucketName, objectName string, opts minio.StatObjectOptions) (minio.ObjectInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatObject", ctx, bucketName, objectName, opts)
	ret0, _ := ret[0].(minio.ObjectInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StatObject indicates an expected call of StatObject.
func (mr *MockMinIOClientMockRecorder) StatObject(ctx, bucketName, objectName, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatObject", reflect.TypeOf((*MockMinIOClient)(nil).StatObject), ctx, bucketName, objectName, opts)
}
