// Code generated by MockGen. DO NOT EDIT.
// Source: internal/queue/activity_event.go
//
// Generated by this command:
//
//	mockgen -source=internal/queue/activity_event.go -destination=internal/queue/mock/activity_event_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockActivityEventRecorder is a mock of ActivityEventRecorder interface.
type MockActivityEventRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockActivityEventRecorderMockRecorder
	isgomock struct{}
}

// MockActivityEventRecorderMockRecorder is the mock recorder for MockActivityEventRecorder.
type MockActivityEventRecorderMockRecorder struct {
	mock *MockActivityEventRecorder
}

// NewMockActivityEventRecorder creates a new mock instance.
func NewMockActivityEventRecorder(ctrl *gomock.Controller) *MockActivityEventRecorder {
	mock := &MockActivityEventRecorder{ctrl: ctrl}
	mock.recorder = &MockActivityEventRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityEventRecorder) EXPECT() *MockActivityEventRecorderMockRecorder {
	return m.recorder
}

// RecordActivityEvent mocks base method.
func (m *MockActivityEventRecorder) RecordActivityEvent(ctx context.Context, userID uuid.UUID, eventType string, streamID *uuid.UUID, payload any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordActivityEvent", ctx, userID, eventType, streamID, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordActivityEvent indicates an expected call of RecordActivityEvent.
func (mr *MockActivityEventRecorderMockRecorder) RecordActivityEvent(ctx, userID, eventType, streamID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordActivityEvent", reflect.TypeOf((*MockActivityEventRecorder)(nil).RecordActivityEvent), ctx, userID, eventType, streamID, payload)
}
