// Code generated by MockGen. DO NOT EDIT.
// Source: export_task_distributor.go
//
// Generated by this command:
//
//	mockgen -source=export_task_distributor.go -destination=mock/export_task_distributor_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockExportTaskDistributor is a mock of ExportTaskDistributor interface.
type MockExportTaskDistributor struct {
	ctrl     *gomock.Controller
	recorder *MockExportTaskDistributorMockRecorder
	isgomock struct{}
}

// MockExportTaskDistributorMockRecorder is the mock recorder for MockExportTaskDistributor.
type MockExportTaskDistributorMockRecorder struct {
	mock *MockExportTaskDistributor
}

// NewMockExportTaskDistributor creates a new mock instance.
func NewMockExportTaskDistributor(ctrl *gomock.Controller) *MockExportTaskDistributor {
	mock := &MockExportTaskDistributor{ctrl: ctrl}
	mock.recorder = &MockExportTaskDistributorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExportTaskDistributor) EXPECT() *MockExportTaskDistributorMockRecorder {
	return m.recorder
}

// DistributeVideoExport mocks base method.
func (m *MockExportTaskDistributor) DistributeVideoExport(ctx context.Context, streamUUID, ownerUUID uuid.UUID, ownerEmail string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DistributeVideoExport", ctx, streamUUID, ownerUUID, ownerEmail)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DistributeVideoExport indicates an expected call of DistributeVideoExport.
func (mr *MockExportTaskDistributorMockRecorder) DistributeVideoExport(ctx, streamUUID, ownerUUID, ownerEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeVideoExport", reflect.TypeOf((*MockExportTaskDistributor)(nil).DistributeVideoExport), ctx, streamUUID, ownerUUID, ownerEmail)
}
