// Code generated by MockGen. DO NOT EDIT.
// Source: task_distributor.go
//
// Generated by this command:
//
//	mockgen -source=task_distributor.go -destination=mock/task_distributor_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskDistributor is a mock of TaskDistributor interface.
type MockTaskDistributor struct {
	ctrl     *gomock.Controller
	recorder *MockTaskDistributorMockRecorder
	isgomock struct{}
}

// MockTaskDistributorMockRecorder is the mock recorder for MockTaskDistributor.
type MockTaskDistributorMockRecorder struct {
	mock *MockTaskDistributor
}

// NewMockTaskDistributor creates a new mock instance.
func NewMockTaskDistributor(ctrl *gomock.Controller) *MockTaskDistributor {
	mock := &MockTaskDistributor{ctrl: ctrl}
	mock.recorder = &MockTaskDistributorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskDistributor) EXPECT() *MockTaskDistributorMockRecorder {
	return m.recorder
}

// DistributeVideoTranscoding mocks base method.
func (m *MockTaskDistributor) DistributeVideoTranscoding(ctx context.Context, streamUUID uuid.UUID, inputPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DistributeVideoTranscoding", ctx, streamUUID, inputPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeVideoTranscoding indicates an expected call of DistributeVideoTranscoding.
func (mr *MockTaskDistributorMockRecorder) DistributeVideoTranscoding(ctx, streamUUID, inputPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeVideoTranscoding", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeVideoTranscoding), ctx, streamUUID, inputPath)
}
