// Code generated by MockGen. DO NOT EDIT.
// Source: task_distributor.go
//
// Generated by this command:
//
//	mockgen -source=task_distributor.go -destination=mock/task_distributor_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskDistributor is a mock of TaskDistributor interface.
type MockTaskDistributor struct {
	ctrl     *gomock.Controller
	recorder *MockTaskDistributorMockRecorder
	isgomock struct{}
}

// MockTaskDistributorMockRecorder is the mock recorder for MockTaskDistributor.
type MockTaskDistributorMockRecorder struct {
	mock *MockTaskDistributor
}

// NewMockTaskDistributor creates a new mock instance.
func NewMockTaskDistributor(ctrl *gomock.Controller) *MockTaskDistributor {
	mock := &MockTaskDistributor{ctrl: ctrl}
	mock.recorder = &MockTaskDistributorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskDistributor) EXPECT() *MockTaskDistributorMockRecorder {
	return m.recorder
}

// DistributeFacesProcessor mocks base method.
func (m *MockTaskDistributor) DistributeFacesProcessor(ctx context.Context, streamUUID uuid.UUID, inputPath string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DistributeFacesProcessor", ctx, streamUUID, inputPath)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DistributeFacesProcessor indicates an expected call of DistributeFacesProcessor.
func (mr *MockTaskDistributorMockRecorder) DistributeFacesProcessor(ctx, streamUUID, inputPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeFacesProcessor", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeFacesProcessor), ctx, streamUUID, inputPath)
}

// DistributeThumbsnailProcessor mocks base method.
func (m *MockTaskDistributor) DistributeThumbsnailProcessor(ctx context.Context, streamUUID uuid.UUID, inputPath string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DistributeThumbsnailProcessor", ctx, streamUUID, inputPath)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DistributeThumbsnailProcessor indicates an expected call of DistributeThumbsnailProcessor.
func (mr *MockTaskDistributorMockRecorder) DistributeThumbsnailProcessor(ctx, streamUUID, inputPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeThumbsnailProcessor", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeThumbsnailProcessor), ctx, streamUUID, inputPath)
}

// DistributeVideoTranscoding mocks base method.
func (m *MockTaskDistributor) DistributeVideoTranscoding(ctx context.Context, streamUUID uuid.UUID, inputPath string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DistributeVideoTranscoding", ctx, streamUUID, inputPath)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DistributeVideoTranscoding indicates an expected call of DistributeVideoTranscoding.
func (mr *MockTaskDistributorMockRecorder) DistributeVideoTranscoding(ctx, streamUUID, inputPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeVideoTranscoding", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeVideoTranscoding), ctx, streamUUID, inputPath)
}

// ReprocessFacesProcessor mocks base method.
func (m *MockTaskDistributor) ReprocessFacesProcessor(ctx context.Context, streamUUID uuid.UUID, inputPath string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReprocessFacesProcessor", ctx, streamUUID, inputPath)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReprocessFacesProcessor indicates an expected call of ReprocessFacesProcessor.
func (mr *MockTaskDistributorMockRecorder) ReprocessFacesProcessor(ctx, streamUUID, inputPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReprocessFacesProcessor", reflect.TypeOf((*MockTaskDistributor)(nil).ReprocessFacesProcessor), ctx, streamUUID, inputPath)
}

// ReprocessThumbsnailProcessor mocks base method.
func (m *MockTaskDistributor) ReprocessThumbsnailProcessor(ctx context.Context, streamUUID uuid.UUID, inputPath string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReprocessThumbsnailProcessor", ctx, streamUUID, inputPath)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReprocessThumbsnailProcessor indicates an expected call of ReprocessThumbsnailProcessor.
func (mr *MockTaskDistributorMockRecorder) ReprocessThumbsnailProcessor(ctx, streamUUID, inputPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReprocessThumbsnailProcessor", reflect.TypeOf((*MockTaskDistributor)(nil).ReprocessThumbsnailProcessor), ctx, streamUUID, inputPath)
}

// ReprocessVideoTranscoding mocks base method.
func (m *MockTaskDistributor) ReprocessVideoTranscoding(ctx context.Context, streamUUID uuid.UUID, inputPath string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReprocessVideoTranscoding", ctx, streamUUID, inputPath)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReprocessVideoTranscoding indicates an expected call of ReprocessVideoTranscoding.
func (mr *MockTaskDistributorMockRecorder) ReprocessVideoTranscoding(ctx, streamUUID, inputPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReprocessVideoTranscoding", reflect.TypeOf((*MockTaskDistributor)(nil).ReprocessVideoTranscoding), ctx, streamUUID, inputPath)
}

// TerminateTask mocks base method.
func (m *MockTaskDistributor) TerminateTask(ctx context.Context, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TerminateTask", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TerminateTask indicates an expected call of TerminateTask.
func (mr *MockTaskDistributorMockRecorder) TerminateTask(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TerminateTask", reflect.TypeOf((*MockTaskDistributor)(nil).TerminateTask), ctx, taskID)
}
