# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: go-app
data:
  MINIO_SERVER_URL: "http://minio.go-app.svc.cluster.local:9000"
  MINIO_BROWSER: "on"
  MINIO_BROWSER_REDIRECT_URL: "https://console.storage.example.com"
  MINIO_DOMAIN: "minio"
  MINIO_PROMETHEUS_AUTH_TYPE: "public"
  MINIO_PROMETHEUS_URL: "http://minio:9000"
  MINIO_REGION: "us-east-1"
  MINIO_API_CORS_ALLOW_ORIGIN: "https://go-app.example.com"
  MINIO_API_CORS_ALLOW_HEADERS: "Authorization,Content-Type,X-Amz*"
  MINIO_API_CORS_ALLOW_METHODS: "GET,PUT,POST,DELETE,OPTIONS,HEAD"
---

