# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: go-app-config
  namespace: go-app
data:
  MINIO_ENDPOINT: "storage.example.com"
  MINIO_BUCKET_NAME: "go-app-bucket"
  MINIO_USE_SSL: "true"
  MINIO_REGION: "us-east-1"
---

