apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: go-app
  labels:
    app: minio
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: hostpath
  volumeName: pvc-632668b5-ecf5-4603-ab0e-b1301274b786
