apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: go-app
type: Opaque
stringData:
  MINIO_ROOT_USER: "admin"
  MINIO_ROOT_PASSWORD: "Master1234"
  MINIO_ACCESS_KEY: "stream-app-1769055983"
  MINIO_SECRET_KEY: "zQYEM67UJ6J2foZjfKnI7KGjDFxmwzGCeF3+DS+zpOg="
---

