apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: go-app
type: Opaque
stringData:
  root-user: "admin"
  root-password: "Master1234"
  access-key: "AKIAIOSFODNN7EXAMPLE"
  secret-key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
---

