// Code generated by MockGen. DO NOT EDIT.
// Source: stream_repository.go
//
// Generated by this command:
//
//	mockgen -source=stream_repository.go -destination=./mock/stream_repository_mock.go -package=repomock
//

// Package repomock is a generated GoMock package.
package repomock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	models "github.com/mrhumster/stream-service/internal/domain/models"
	repository "github.com/mrhumster/stream-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockStreamRepository is a mock of StreamRepository interface.
type MockStreamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStreamRepositoryMockRecorder
	isgomock struct{}
}

// MockStreamRepositoryMockRecorder is the mock recorder for MockStreamRepository.
type MockStreamRepositoryMockRecorder struct {
	mock *MockStreamRepository
}

// NewMockStreamRepository creates a new mock instance.
func NewMockStreamRepository(ctrl *gomock.Controller) *MockStreamRepository {
	mock := &MockStreamRepository{ctrl: ctrl}
	mock.recorder = &MockStreamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamRepository) EXPECT() *MockStreamRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStreamRepository) Create(ctx context.Context, stream *models.Stream) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, stream)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStreamRepositoryMockRecorder) Create(ctx, stream any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStreamRepository)(nil).Create), ctx, stream)
}

// Delete mocks base method.
func (m *MockStreamRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStreamRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStreamRepository)(nil).Delete), ctx, id)
}

// Exists mocks base method.
func (m *MockStreamRepository) Exists(ctx context.Context, id uuid.UUID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Exists indicates an expected call of Exists.
func (mr *MockStreamRepositoryMockRecorder) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockStreamRepository)(nil).Exists), ctx, id)
}

// GetByOwner mocks base method.
func (m *MockStreamRepository) GetByOwner(ctx context.Context, ownerID uuid.UUID) ([]*models.Stream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOwner", ctx, ownerID)
	ret0, _ := ret[0].([]*models.Stream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOwner indicates an expected call of GetByOwner.
func (mr *MockStreamRepositoryMockRecorder) GetByOwner(ctx, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOwner", reflect.TypeOf((*MockStreamRepository)(nil).GetByOwner), ctx, ownerID)
}

// IncrementViews mocks base method.
func (m *MockStreamRepository) IncrementViews(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementViews", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementViews indicates an expected call of IncrementViews.
func (mr *MockStreamRepositoryMockRecorder) IncrementViews(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementViews", reflect.TypeOf((*MockStreamRepository)(nil).IncrementViews), ctx, id)
}

// List mocks base method.
func (m *MockStreamRepository) List(ctx context.Context, filter repository.StreamFilter) ([]*models.Stream, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*models.Stream)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockStreamRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStreamRepository)(nil).List), ctx, filter)
}

// Read mocks base method.
func (m *MockStreamRepository) Read(ctx context.Context, id uuid.UUID) (*models.Stream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx, id)
	ret0, _ := ret[0].(*models.Stream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockStreamRepositoryMockRecorder) Read(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockStreamRepository)(nil).Read), ctx, id)
}

// Update mocks base method.
func (m *MockStreamRepository) Update(ctx context.Context, stream *models.Stream) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, stream)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStreamRepositoryMockRecorder) Update(ctx, stream any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStreamRepository)(nil).Update), ctx, stream)
}

// UpdateProcessing mocks base method.
func (m *MockStreamRepository) UpdateProcessing(ctx context.Context, id uuid.UUID, processing models.StreamProcessing) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProcessing", ctx, id, processing)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProcessing indicates an expected call of UpdateProcessing.
func (mr *MockStreamRepositoryMockRecorder) UpdateProcessing(ctx, id, processing any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProcessing", reflect.TypeOf((*MockStreamRepository)(nil).UpdateProcessing), ctx, id, processing)
}

// UpdateStatus mocks base method.
func (m *MockStreamRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status models.StreamStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockStreamRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockStreamRepository)(nil).UpdateStatus), ctx, id, status)
}
