// Code generated by MockGen. DO NOT EDIT.
// Source: stream_export_repository.go
//
// Generated by this command:
//
//	mockgen -source=stream_export_repository.go -destination=./mock/stream_export_repository_mock.go -package=repomock
//

// Package repomock is a generated GoMock package.
package repomock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	models "github.com/mrhumster/stream-service/internal/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockStreamExportRepository is a mock of StreamExportRepository interface.
type MockStreamExportRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStreamExportRepositoryMockRecorder
	isgomock struct{}
}

// MockStreamExportRepositoryMockRecorder is the mock recorder for MockStreamExportRepository.
type MockStreamExportRepositoryMockRecorder struct {
	mock *MockStreamExportRepository
}

// NewMockStreamExportRepository creates a new mock instance.
func NewMockStreamExportRepository(ctrl *gomock.Controller) *MockStreamExportRepository {
	mock := &MockStreamExportRepository{ctrl: ctrl}
	mock.recorder = &MockStreamExportRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamExportRepository) EXPECT() *MockStreamExportRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStreamExportRepository) Create(ctx context.Context, export *models.StreamExport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, export)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStreamExportRepositoryMockRecorder) Create(ctx, export any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStreamExportRepository)(nil).Create), ctx, export)
}

// ReadByStream mocks base method.
func (m *MockStreamExportRepository) ReadByStream(ctx context.Context, streamID uuid.UUID) (*models.StreamExport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadByStream", ctx, streamID)
	ret0, _ := ret[0].(*models.StreamExport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadByStream indicates an expected call of ReadByStream.
func (mr *MockStreamExportRepositoryMockRecorder) ReadByStream(ctx, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadByStream", reflect.TypeOf((*MockStreamExportRepository)(nil).ReadByStream), ctx, streamID)
}

// ResetFailed mocks base method.
func (m *MockStreamExportRepository) ResetFailed(ctx context.Context, exportID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetFailed", ctx, exportID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetFailed indicates an expected call of ResetFailed.
func (mr *MockStreamExportRepositoryMockRecorder) ResetFailed(ctx, exportID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetFailed", reflect.TypeOf((*MockStreamExportRepository)(nil).ResetFailed), ctx, exportID)
}

// Update mocks base method.
func (m *MockStreamExportRepository) Update(ctx context.Context, export *models.StreamExport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, export)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStreamExportRepositoryMockRecorder) Update(ctx, export any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStreamExportRepository)(nil).Update), ctx, export)
}
